Upgrade ingress addon
canonical/microk8s-core-addons pull request #123
Opened 2022-11-11 07:12 UTC by dud225

- Switch to a Helm-based installation. That will help to relieve the
  project of the maintenance burden as by default the latest chart
  version is picked. If case of trouble the user can override the chart
  version to install.
- Set up the admission controller by default. This helps to detect
  invalid configurations early, see
https://kubernetes.github.io/ingress-nginx/how-it-works/#avoiding-outage-from-wrong-configuration.
  It can be disabled at addon installation time to get a configuration
  similar to what is set up so far.
- breaking change: the metrics endpoint is no longer exposed on the host
  (hostPort), instead it is exposed internally only through a ClusterIP
  service. Note that it is fairly easy to expose it externally though an
  Ingress.
- Put back the nginx IngressClass as the default (fixes
  https://github.com/canonical/microk8s/issues/2035).

2022-11-11 09:56 UTC, neoaggelos requested changes
Thank you for this PR @dud225.

I have not reviewed this yet, will do after CI is successful. In general, I am not opposed to using the nginx-ingress helm chart for this, but I am a bit wary about the implicit dependency on `https://kubernetes.github.io/ingress-nginx` being reachable when enabling the ingress addon. This might not be the case for enterprise, firewall-ed, airgap environments etc, and this change would break existing flows.

I am not sure how best to tackle this, including the helm chart could be an option.

2022-11-12 09:53 UTC, dud225 commented
> I have not reviewed this yet, will do after CI is successful. In general, I am not opposed to using the nginx-ingress helm chart for this, but I am a bit wary about the implicit dependency on `https://kubernetes.github.io/ingress-nginx` being reachable when enabling the ingress addon. This might not be the case for enterprise, firewall-ed, airgap environments etc, and this change would break existing flows.
> 
> I am not sure how best to tackle this, including the helm chart could be an option.

I do agree with you and, to be honest, I'm also concerned by the fact that the latest chart version is pulled by default, which means that depending on the time the user installs the addon, 2 different users may not get the same result despite running on the same Microk8s version.

However this approach has benefits for the Microk8s project : much less maintenance cost since the latest chart is pulled and most importantly much more flexibility for the user since custom values can be passed along.

I thought that there was an agreement on this approach as this is currently what has been done on the observability addon: https://github.com/canonical/microk8s-core-addons/blob/f9d2f4bcc3ee4059dff701df8681651a81dd72e5/addons/observability/enable#L39-L56
I also [brought this topic on Slack](https://kubernetes.slack.com/archives/CAUNWQ85V/p1666080465371469) and, albeit this specific point wasn't discussed, the answer I got made me believe this approach was palatable.

I'd suggest that you discuss this internally to clarify that matter.

2022-11-15 06:30 UTC, dud225 commented
The CI has been fixed.

2022-11-18 17:10 UTC, neoaggelos commented
> I also [brought this topic on Slack](https://kubernetes.slack.com/archives/CAUNWQ85V/p1666080465371469) and, albeit this specific point wasn't discussed, the answer I got made me believe this approach was palatable.
> I'd suggest that you discuss this internally to clarify that matter.

Looking at the conversation, using upstream Helm charts is indeed something we consider and are positive towards. The issue is with implicitly adding dependencies that might break existing workflows. :)

Any thoughts @ktsakalozos?

2022-11-18 21:43 UTC, dud225 commented
We could store a copy of the chart to install, much as the manifest, but then the addon will constantly trail behind the latest upstream version. For a small and mature addon this is OK, but for a more active one like this one it is suboptimal.

2022-11-29 14:41 UTC, ktsakalozos commented
Thank you for this work @dud225. You an @neoaggelos bring up valid concerns.

The biggest show stopper for me is the deployment of the "latest" stable ingress release. Looking at the ingress releases I see the support for k8s v1.19 was dropped with the v1.24 release. This makes sense however when looking at what people deploy we see a significant amount of users still using/deploying v1.19. Following the "latest" would have made more sense in rolling k8s distributions but MicroK8s is not one.

2022-11-29 14:54 UTC, dud225 commented
Thanks for your acknowledgements.
When you wrote "using/deploying v1.19" you mean MicroK8s version 1.19 don't you? If so the addon repository is frozen alongside MicroK8s when the snap is built, so that the users using this version will still be pointed to the ingress addon that was in the repo at that time, isn't that correct? Tell me if I'm missing something.
Otherwise I can fix the ingress version to one that suits if pulling a chart is fine for you.

2022-11-29 15:38 UTC, dud225 commented
Thanks the comment that's now clear.

> to address airgapped usecases the helm packages should be in the snap.

How to do this? Shall I copy/paste the chart into the repo? Or is there a build script that should be modified to handle this?

2022-11-30 08:24 UTC, ktsakalozos commented
> How to do this?

The mayastor addon on this repo is a good example.

2022-11-30 13:06 UTC, dud225 commented
I've vendored the ingress-nginx Helm chart version 4.4.0.

2025-04-09 13:05 UTC, louiseschmidtgen commented
Hi @dud225,

thank you for your work on updating the ingress addon.

We've recently updated the addon in https://github.com/canonical/microk8s-core-addons/commit/b320ee5461e7dba9749409167d7989cba7f42d0b.

Please create a new PR for any future contributions.

Best regards,
Louise

2025-04-09 13:05 UTC, closed without merging